[tool.poetry]
name = "zpodsdk"
version = "0.1.0"
description = "A client library for accessing zPod API"

authors = []

readme = "README.md"
packages = [
    {include = "zpod"},
]
include = ["CHANGELOG.md", "zpod/py.typed"]

[tool.poetry.dependencies]
python = "^3.8.1"
httpx = "0.25.0"
attrs = "23.1.0"
python-dateutil = "2.8.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
